name: Test (External)
on:
  push:
    paths-ignore: [docs/]
  pull_request:
    paths-ignore: [docs/]

jobs:
  skip_dup_run:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: same_content
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build:
    needs: skip_dup_run
    if: ${{ needs.skip_dup_run.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r testing/requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest testing/external -s
